name: Manual Triggered Job

on:
  workflow_dispatch:

jobs:
  manual_triggered_job:
    runs-on: ubuntu-latest

    steps:
      - name: Run the manual triggered job
        run: echo "This job was manually triggered"
